# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48ff7fd3ead8e58f416c19e804a60a50a81ca997b9e82154500ba20bfc087c80da5b40690b9ba0871c9e2b8821acf344204f7236f3c4533c7945012471dc3f8c

test:
  secret_key_base: 1ee7792a43711a06e9d2f54fc300c95168f1f453266b82463d491206c7a436b1a0548dea1c46bd02e2e195df91bc82c0c219e40c237efd28357ddd5664af0327

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
